trigger:
  branches:
    include:
      - main

 

pool:
  vmImage: "ubuntu-latest"

 

variables:
  registryConnection: empowerserviceconnection
  imageName: searchservice

 

steps:
  - task: Docker@2
    displayName: "Build image"
    inputs:
      repository: $(imageName)
      containerRegistry: $(registryConnection)
      command: buildAndPush
      Dockerfile: Dockerfile
      tags: latest

  - task: PublishPipelineArtifact@1
    inputs:
      pathToPublish: 'Search.Service/Manifest'
      artifact: 'manifests'