apiVersion: v1
kind: Service
metadata:
  name: searchservice-application
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: 80
  selector:
    app: searchservice-application
  type: LoadBalancer